Launcher fixes2
vcmi/vcmi pull request #1028
Opened 2022-10-01 07:32 UTC by DjWarmonger

Rebase of #822

- Fixed resizing of toolbar: https://bugs.vcmi.eu/view.php?id=2728
- Fixed icon update when a sub-mod is enabled or disabled: https://bugs.vcmi.eu/view.php?id=3217

2022-10-01 09:25 UTC, kambala-decapitator approved these changes

2022-10-01 15:05 UTC, nullkiller requested changes
![image](https://user-images.githubusercontent.com/5644734/193415757-bf488379-c683-4bcd-ab44-91e17d840bd2.png)
red signs should be only for installed disabled mods. This works correct now but is broken in this branch.

2022-10-01 15:05 UTC, kambala-decapitator commented on launcher/modManager/cmodlist.cpp
> -		return false;
seems this change broke existing behavior

2022-10-01 15:06 UTC, nullkiller commented
More over pressing <<Enable>>causes error message

2022-10-01 18:42 UTC, DjWarmonger commented
@nullkiller How do I actually get that long list of mods to download?

2022-10-01 19:11 UTC, kambala-decapitator commented
> @nullkiller How do I actually get that long list of mods to download?

add https://raw.githubusercontent.com/vcmi/vcmi-mods-repository/develop/beta.json to the repositories list

2022-10-01 19:29 UTC, nullkiller commented
new vcpkg is already here with working TLS

2022-10-01 19:31 UTC, DjWarmonger commented
Oh, I'll need this too.

2024-06-21 00:32 UTC, Alexander-Wilms commented
Both bugs are fixed by now, I think the MR can be closed.

With a screen resolution of 800x600:

![image](https://github.com/vcmi/vcmi/assets/3226457/83ebd636-265f-4abe-abdf-f0dc6f0133f0)

2025-02-27 19:57 UTC, closed without merging