Added pressing and deleting with the [DELETE] key
vcmi/vcmi pull request #1433
Opened 2023-01-14 21:38 UTC by SergeyG22

added pressing and deleting with the [DELETE] key (issue #1356 [DELETE] key doesn't work in map editor)

2023-01-15 07:03 UTC, kambala-decapitator requested changes
the approach itself looks good

2023-01-15 07:03 UTC, kambala-decapitator commented on mapeditor/mainwindow.cpp
> +void MainWindow::keyPressEvent(QKeyEvent* event)
according to our current [coding guidelines](https://wiki.vcmi.eu/Coding_guidelines#Where_to_put_spaces) should be:
```suggestion
void MainWindow::keyPressEvent(QKeyEvent * event)
```

2023-01-15 07:03 UTC, kambala-decapitator commented on mapeditor/mainwindow.h
> +	virtual void keyPressEvent(QKeyEvent* event);
```suggestion

protected:
	virtual void keyPressEvent(QKeyEvent * event);
```

2023-01-15 21:54 UTC, Nordsoft91 commented
Seems like delete and backspace are handled differently. Is it possible to handle them in same way?
Also, is it possible to define hotkey for button as it done for all other actions?

2023-01-16 02:42 UTC, SergeyG22 commented
'delete' and 'backspace' are handled differently because calling 'backspace' in a standard event loop doesn't work properly. Perhaps installing an event filter will solve this. But I do not know how to do it. The easiest way I've found is to use a hotkey.

2023-01-16 08:51 UTC, kambala-decapitator commented
> 'delete' and 'backspace' are handled differently because calling 'backspace' in a standard event loop doesn't work properly. 

at least on macOS I don't see any issues with the following test code:

```cpp
#include <QtWidgets>

class MainWindow : public QMainWindow
{
protected:
	virtual void keyPressEvent(QKeyEvent* e) override
	{
		switch (e->key())
		{
		case Qt::Key_Backspace:
			qDebug("Key_Backspace");
			break;
		default:
			QMainWindow::keyPressEvent(e);
			break;
		}
	}
};

int main(int argc, char* argv[])
{
	QApplication a{argc, argv};
	MainWindow w;
	w.show();
	return a.exec();
}
```

> Perhaps installing an event filter will solve this.

`keyPressEvent` method is identical to handling key presses in event filter

> please handle Backspace key on macOS instead

my original intention was to handle Backspace on macOS and Delete on other platforms (`#ifdef` would've been the easiest solution), sorry for not being clear. I'd suggest to just do this removing all the complexity of the last commit.

2023-01-16 10:23 UTC, SergeyG22 commented
I don't have a macOS distribution. What you have given works well in the test project. Try adding a 'delete' handler to this code there as well. Still working? And now do the same in the map designer. The bundle of delete and backspace does not work on Windows 10. It seems that backspace is in conflict with something. I don't know anything about Mac. It's not just that I took out the backspace in the hotkey.

2023-01-16 14:24 UTC, kambala-decapitator commented
I'll test how Backspace behaves in the editor on macOS

2023-01-17 09:24 UTC, kambala-decapitator commented
@SergeyG22 have you tested erase functionality? For me it doesn't work at all on macOS - tried from toolbar, from menu, from instrument palette, with the new shortcut... @Nordsoft91 does it work for you?

btw you can attach key sequence directly to the action, no need to add a separate one or handle key event on main window. I also see that current shortcut is "press backspace, then press delete" which is obviously wrong.

2023-01-17 19:46 UTC, kambala-decapitator commented
@SergeyG22 so, does erase work for you on your OS?

@Nordsoft91 and what about you on macOS?

2023-01-18 08:46 UTC, SergeyG22 commented
![bandicam 2023-01-18 11-41-57-868](https://user-images.githubusercontent.com/46799640/213125066-cfd61f1e-9e79-4378-afb9-01d45f7753f1.gif)

2023-01-18 09:00 UTC, kambala-decapitator commented
thanks, I'm stupid: I was trying to erase land instead of objects =)

> btw you can attach key sequence directly to the action, no need to add a separate one or handle key event on main window. I also see that current shortcut is "press backspace, then press delete" which is obviously wrong.

so let's do this:
1. remove all your changes
2. remove shortcut of erase action from the .ui file
3. in code (in constructor) give the action Backspace key sequence on macOS and Delete on other platforms using `#ifdef`

2023-01-18 13:03 UTC, SergeyG22 commented
I'll do it as I have free time

2023-02-01 20:31 UTC, Nordsoft91 approved these changes
We can keep as is

2023-02-02 07:45 UTC, kambala-decapitator commented
> We can keep as is

don't see any reason to bloat code with strange workarounds when doing things right is trivial

2023-03-06 15:54 UTC, Nordsoft91 commented
Fixed in other PR

2023-03-06 15:54 UTC, closed without merging