Get next visible bound portal feature
vcmi/vcmi pull request #2795
Opened 2023-09-10 04:26 UTC by david-shiko

**Summary**
This PR introduces the GetNextVisibleBoundPortalFeature, which enhances the user's navigation experience in the adventure map. Now, right-clicking on any portal will sequentially move the screen to the next exit/entrance, providing a more intuitive way to understand portal connections.

**Future Work**
1. Implement long/short click to distinguish between original behavior (show caption on long press) and show next portal (on short click).
2. Remove focus/selection from hero after viewing next portal exit. This will help to easily return scsreen to the hero (rather than opening hero window).

Multiple exits may necessitate splitting the info window into additional windows.
The info window doesn't display the location on the map and the minimap.
Implementing this feature via the info window may require more time.

2023-09-10 22:46 UTC, Nordsoft91 commented on lib/mapObjects/MiscObjects.cpp
> +	return std::nullopt;
adjust indentation

2023-09-10 22:46 UTC, Nordsoft91 commented on lib/mapObjects/MiscObjects.cpp
> +	catch (const std::exception& e) {
which functions throws here?

2023-09-10 22:46 UTC, Nordsoft91 commented on lib/mapping/MapReaderH3M.cpp
> -	assert(result.getNum() < features.heroesPortraitsCount);
why remove?

2023-09-10 22:46 UTC, Nordsoft91 commented on client/adventureMap/AdventureMapInterface.cpp
> +			if (closestExit.has_value()) {
There are some coding guidelines https://wiki.vcmi.eu/Coding_guidelines.

Please, put braces from next line

2023-09-10 22:47 UTC, Nordsoft91 commented
> Implement long/short click to distinguish between original behavior (show caption on long press) and show next portal (on short click).

do you plan to make it in scope of this PR?

2023-09-11 09:16 UTC, IvanSavenko commented on lib/mapObjects/MiscObjects.cpp
> +	catch (...) {
Don't use "catch everything" unless there is a strong reason to

2023-09-11 09:27 UTC, IvanSavenko reviewed
I think following approach should be better and more in-line with H3 UX:

- **Left-click**: no change - set path / move hero

- **Ctrl+Left-click**: 
- - if there is a discovered exit - switch map view to next exit
- - if there are no known exits - do nothing

- **Right-click**: 
- - If there is a discovered exit: show text "Monolith \n (Ctrl+click to switch to next exit)"
- - If there are no known exits: no change, show text "Monolith"

- **Hovering**: should display same text as right-click

For mobile - not available right now, will try to make radial menu similar to garrisons for adventure map by 1.4 release

2023-09-11 09:28 UTC, IvanSavenko commented on lib/mapObjects/MiscObjects.cpp
> +			break;
What if portal have (for example) 1 exits but multiple entrances? Will player be able to navigate through all entrances?

2023-09-11 16:29 UTC, Nordsoft91 requested changes
Tested on map attached: 
[test_monoliths_2.vmap.zip](https://github.com/vcmi/vcmi/files/12578433/test_monoliths_2.vmap.zip)

1. Visit sign -> right click on blue entrance, observe jump on invisible exit
2. Both exits and entrances for one-way portals doesn't work properly
3. For bi-directional portals works well

2023-09-12 19:16 UTC, david-shiko commented
> > Implement long/short click to distinguish between original behavior (show caption on long press) and show next portal (on short click).
> 
> do you plan to make it in scope of this PR?

No, I think it should be a separate branch for handling the new input source, which I'll merge into this branch.

2023-09-12 20:49 UTC, IvanSavenko commented
> > > Implement long/short click to distinguish between original behavior (show caption on long press) and show next portal (on short click).
> > 
> > 
> > do you plan to make it in scope of this PR?
> 
> No, I think it should be a separate branch for handling the new input source, which I'll merge into this branch.

Please consider approach I described here: https://github.com/vcmi/vcmi/pull/2795#pullrequestreview-1619532001

No need for custom input source. Especially since mobiles already have both short and long tap  - which function similar to left & right click.

2026-05-24 17:35 UTC, closed without merging