Allow configuring all objects
vcmi/vcmi pull request #3115
Opened 2023-10-27 23:24 UTC by Nordsoft91

All rewardable objects are possible to customise in map editor.

Also, fixes #3087

2023-10-27 23:58 UTC, Laserlicht commented on mapeditor/mainwindow.cpp
> +		lastSavingDir = QString::fromStdString(VCMIDirs::get().userCachePath().make_preferred().string());
```suggestion
		lastSavingDir = QString::fromStdString(VCMIDirs::get().userDataPath().make_preferred().string());
```
Shouldn't it DataPath?

2023-10-29 13:02 UTC, IvanSavenko commented
Do we embed configuration for all objects into vmap?
So if I use a mod that modifies Witch Hut then these changes won't have effect on vmap's made without such mod?

2023-11-05 14:04 UTC, IvanSavenko requested changes

2023-11-05 14:04 UTC, IvanSavenko commented on lib/mapObjectConstructors/CRewardableConstructor.cpp
> +
This will break reroll of revisitable objects, e.g. Windmills

2026-05-24 17:40 UTC, closed without merging