Autodetect and autocopy installed heroes on windows
vcmi/vcmi pull request #3442
Opened 2024-01-05 22:43 UTC by Laserlicht

fixes  #3437

2024-01-05 22:44 UTC, dydzio0614 commented
hopefully somebody can test this manually (no windows here)

2024-01-05 22:46 UTC, Laserlicht commented
> hopefully somebody can test this manually (no windows here)

Tested the first commit. Will retest after CI is done.

But would be great if someone other than me also could test.

2024-01-05 23:50 UTC, Laserlicht commented
Tested following on my Win7 32bit VM:
- Installed CD version
- Installed GOG version
- Without installed H3 (data in custom folder)

Works!

2024-01-06 06:35 UTC, kambala-decapitator approved these changes
use `{}` or `QString{}` instead of empty string literals

2024-01-06 11:07 UTC, IvanSavenko commented
Perhaps show confirmation query instead of silent copy?

Not against silent copy, but not sure if this is a good idea.

2024-01-06 14:50 UTC, Laserlicht commented
Added Question-Box

2024-01-06 16:43 UTC, kambala-decapitator requested changes

2024-01-06 16:43 UTC, kambala-decapitator commented on launcher/firstLaunch/firstlaunch_moc.cpp
> +		sourceRoot.setPath(QFileDialog::getExistingDirectory(this, "", "", QFileDialog::ShowDirsOnly | QFileDialog::DontResolveSymlinks));
```suggestion
		sourceRoot.setPath(QFileDialog::getExistingDirectory(this, {}, {}, QFileDialog::ShowDirsOnly | QFileDialog::DontResolveSymlinks));
```

2024-01-06 16:43 UTC, kambala-decapitator commented on launcher/firstLaunch/firstlaunch_moc.h
> +	void copyHeroesData(const QString & path = "");
```suggestion
	void copyHeroesData(const QString & path = {});
```

2024-01-06 16:43 UTC, kambala-decapitator commented on launcher/firstLaunch/firstlaunch_moc.cpp
> +		return gogPath;
```suggestion
		return gogPath;

```

2024-01-06 16:43 UTC, kambala-decapitator commented on launcher/firstLaunch/firstlaunch_moc.cpp
> +		reply = QMessageBox::question(this, tr("Heroes III installation found!"), tr("Copy data to VCMI folder?"), QMessageBox::Yes|QMessageBox::No);
```suggestion
		auto reply = QMessageBox::question(this, tr("Heroes III installation found!"), tr("Copy data to VCMI folder?"), QMessageBox::Yes | QMessageBox::No);
```

2024-01-06 21:34 UTC, Laserlicht commented
@kambala-decapitator Thanks. :)

2024-01-10 13:49 UTC, IvanSavenko approved these changes

2024-01-10 13:49 UTC, IvanSavenko commented
@kambala-decapitator is everything OK now?

2024-01-10 14:21 UTC, kambala-decapitator commented
> @kambala-decapitator is everything OK now?

Yep, thanks for reminding

2024-01-10 14:37 UTC, merged

2024-01-10 15:26 UTC, IvanSavenko commented
Not related to this PR strictly speaking - this is how our setup works at the moment. We ask player to point to location of H3 files and copy them.
The only change from this PR is that on Windows vcmi will now automatically find this location.

As for your question - partially historical reasons, partially - this approach is easier:
1) This way we don't have to ask player whether to copy or use data as it. 
2) While on Windows H3 files will probably stay, on other platforms they likely won't - since player likely pointed to files that he have extracted into some temporary directory.
3) Support for using data in-place needs work. Likely easy to do, but that is still time.
4) Frankly, this is 2024, not 2000. Most of players have large enough storage to not care about 1 extra Gb. And if they do - they can create symlinks (or whatever they are called on Windows).

2024-01-10 15:50 UTC, kambala-decapitator commented
> Why copying files?
> 
> Why not just use the resources from there, where is detected?

We have #874 for that

2024-01-10 15:57 UTC, psyhlo commented
thanks and sorry for the spam