Fix exception while calculating paths
vcmi/vcmi pull request #647
Opened 2020-09-11 19:17 UTC by ShubusCorporation

2020-09-12 10:53 UTC, nullkiller commented
Hi. That is strange. Have not seen any errors in pathfinder. It should fail quite frequently but it does not. How about performance? It is performance critical thing for AI.

2020-09-14 17:10 UTC, ShubusCorporation commented
Hi! There're some screenshots I've captured during investigation:
![debug_app_ui](https://user-images.githubusercontent.com/58867270/93116455-f0f80e00-f6c5-11ea-87a1-5a8fd9328353.png)
![vs_after_build](https://user-images.githubusercontent.com/58867270/93116544-11c06380-f6c6-11ea-9323-c85b397c3e35.png)
![vs_call_stack](https://user-images.githubusercontent.com/58867270/93116562-15ec8100-f6c6-11ea-8cb2-1d52b40c27c3.png)
![vs_pq_state](https://user-images.githubusercontent.com/58867270/93116570-184edb00-f6c6-11ea-93f7-7bb02e7a1e9a.png)

2020-09-14 17:25 UTC, ShubusCorporation commented
When I experimentally replaced the Node comparator with a stub (return false), exception gone away. Thus, the root cause is appearance of not sorted data in the pq.

2020-09-14 17:39 UTC, nullkiller commented
But does it crash when you run it in RelWithDebInfo configuration?

2020-09-14 17:47 UTC, nullkiller commented
Also please provide your build details. Was it done with cmake or using sln included into the project. What was the version of boost and so on. You need very strong arguments to use this standalone priority queue instead of boost one. And performance and portability is one of the most tricky questions.
P.S. I am not strong at C++, just touched CPathfinder a bit for AI. Just trying to help you figure it out.

2020-09-14 17:58 UTC, nullkiller commented on lib/CPathfinder.cpp
> +	if (node != NULL && std::find(this->pq.begin(), this->pq.end(), node) == this->pq.end())
Does it mean O(n) complexity for push operation?

2020-09-14 17:58 UTC, nullkiller commented on lib/CPathfinder.cpp
> +	auto result = std::min_element<Iter>(this->pq.cbegin(), this->pq.end(), PriorityQueue::nodeCostComparator);
Does it mean O(n) complexity for pop operation?

2020-09-14 19:04 UTC, ShubusCorporation reviewed
> 
> Also please provide your build details. Was it done with cmake or using sln included into the project. What was the version of boost and so on. 

Firstly, I make it with cmake: `cmake d:\Sources\VCMI\source -DCMAKE_TOOLCHAIN_FILE=d:\Sources\VCMI\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 14 2015 Win64"`
Then I opened  \VCMI\build\VCMI.sln and build it with VS 2015.

Boost was taken from vcpkg from official site.  It seems,  it's  v. 1.64

2020-09-15 06:07 UTC, nullkiller commented
boost priority queue gives logarithmic complexity (linear only in worst case) and this thing is performance critical. The size of the queue on a big map might be about 10K.
Bad order will not cause issues because invalid nodes should be already locked (node.locked == true) and will be just skipped and the thing you see is just a debug assertion which will be disabled in release build.

2020-09-15 19:46 UTC, ShubusCorporation commented
Boost priority queue gives logarithmic complexity (linear only in worst case).
But "worst case" means  case when some  kind of "inconvenient" data is pushed to the PQ, not the case when PQ is used in inappropriate way. In last case it is not a Priority Queue and "PQ complexity " makes no sense. Unlikely, that Boost authors added that assertion just to be ignored.

Locked flag is used to prevent extracted node to be pushed into PQ again (if(neighbour->locked) continue;), it's not related to the sorting issue. Locked nodes are not "invalid", but nodes to which the rules were applied, nodes which already was in queue and was extracted from there.

The current implementation issues:

1) Priority Queue does not work as  Priority Queue. It works as something trying to be "Priority Queue":
    -  Already pushed nodes are subject to change
    - Result of top / pop is not most priority node with min cost, as expected

2) There is no duplicates check. It's enough to move mouse and new duplicate node will be pushed to the queue from the "tileHover" handler. 10K nodes in queue is not a limit in this way.

3) Subjectively. On some random middle map 4x4, template JC  from a certain moment it starts to hang on each object taking.
I suspect this is related to this node loop. It's unknown, how often this issue is  reproducible.

2020-09-15 19:48 UTC, ShubusCorporation commented
![inPQ_BrokenPriority](https://user-images.githubusercontent.com/58867270/93257451-8918f480-f7a5-11ea-9832-27a8392d5a1b.jpg)

2020-09-15 20:00 UTC, ShubusCorporation commented
This is a reason to think about a more optimal solution. Push may be done as O(1) but on the top/pop loss of speed unavoidable because through current implementation it is not known, is queued data sorted or not.

May be there's a sense to make custom queue which will be intercept changing of node cost and perform resorting,
but it's not so easy to determine, how this approach will affect performance.

2020-09-15 20:08 UTC, nullkiller commented
> There is no duplicates check. It's enough to move mouse and new duplicate node will be pushed to the queue from the "tileHover" handler. 10K nodes in queue is not a limit in this way.

Do not understand here. CPathfinder calculates paths to all objects on the map at once. Hover event might trigger pathfinding to check if tile is accessible but it should be only once per each move. The size of the queue depends on how much area it is possible to rich so it will be small at the beginning for a player because it is locked by guards. As more area is accessible as bigger will be the queue size each time pathfinding is invoked.

2020-09-15 20:21 UTC, nullkiller commented
It might be possible to remove node from queue when we want to change its cost and add it back afterwards. If this operation will also be logarithmic it should be more or less ok. What do you think?

Regarding to locked flag logically if we fetched a node from pq it should be the shortest path already and thus it is not possible that somebody finds more short path and wants to add a node back to pq so I think the flag was introduced to avoid duplicates processing.

Do you plan contributing to the project further? Would be nice to talk in slack

2020-09-16 18:00 UTC, ShubusCorporation commented
The duplicates are pointers (more precisely, references to the const pointer) to the same node which is not locked yet. They appears during neighbors processing. Each node is neighbor of each of its neighbors, this is a cause.

Yes, I'm going to become a contributor in and improve this solution. I will provide it asap. 
About Slack, yes I agree, later.

2020-09-17 06:06 UTC, nullkiller commented
One more point I think we can go without top and leave only pop. Should save some cpu ticks. And I hardly recommend you to provide some performance values on a XL map for AI comparing your and old version. The order issue can cause some hardly traceable bugs but I do not think they will be noticeable but AI speed depends on CPathfinder quite much and everybody who play VCMI complains about it.

2020-09-21 13:54 UTC, ShubusCorporation commented
@nullkiller 
Hello, Andrii, take a look pls.

I found, that the Boost offers built-in approaches to update nodes  using PQ based on the mutability heaps. It seems, the Fibonacci heap has best complexity for such goals.

https://www.geeksforgeeks.org/fibonacci-heap-set-1-introduction/

There was more simple solution for interception of the node cost change, but it seems, that the solution from Microsoft 
to create properties "__declspec( property( get=get_func_name ) ) declarator"  is not common (VCMI has to support at least gcc 4.8 )

I have tried to play on different maps (small and XL) with different heaps (binomial and fibonacci). 
It looks, that it works well.

2020-09-21 14:00 UTC, nullkiller commented
@ShubusCorporation
Hi Dmitry.
That looks way different and now I like it. Going to read about this fibonacci heap a bit. Anyway I have no rights to merge anything so lets wait for @alexvins

2020-09-21 18:07 UTC, alexvins requested changes

2020-09-21 18:07 UTC, alexvins commented on lib/CPathfinder.h
> +			return;
Please do not put `{}` around one line blocks

2020-09-21 18:07 UTC, alexvins commented on lib/CPathfinder.h
> +		if (inPQ && pq != nullptr)
No space after `if` please,
```suggestion
		if(inPQ && pq != nullptr)
```

2020-09-21 18:07 UTC, alexvins commented on lib/CPathfinder.h
> +	bool operator()(const N* lhs, const N* rhs) const
```suggestion
	bool operator()(const N * lhs, const N * rhs) const
```

2020-09-21 18:07 UTC, alexvins commented on lib/CPathfinder.h
> +	void push(CGPathNode* node);
```suggestion
	void push(CGPathNode * node);
```

2020-09-21 18:07 UTC, alexvins commented on lib/CPathfinder.h
> +	CGPathNode* topAndPop();
```suggestion
	CGPathNode * topAndPop();
```

2020-09-21 18:07 UTC, alexvins commented on lib/CPathfinder.h
> +		operator float() const {
```suggestion
		operator float() const 
		{
```

2020-09-21 22:23 UTC, alexvins approved these changes
Looks fine, thank you.

2020-09-22 05:42 UTC, nullkiller commented
Ok, I will merge it to my branch and perform some testing

2020-09-22 06:32 UTC, nullkiller commented
Automatic test suit passed, performance degradation on XL map was not noticed.

2020-09-22 06:32 UTC, nullkiller approved these changes

2020-09-22 10:23 UTC, merged