Mod system improvement Part I : Special buildings should work in  modders towns
vcmi/vcmi pull request #652
Opened 2020-09-30 19:34 UTC by ShubusCorporation

These special building are ready to work in the mod towns:

- "stables"
- "brotherhood_of_sword"  (+2 morale)
- "lookout_tower" 
There're 4 types of Tower have been introduced:  
- "high" (R=20), 
- "average" (R=15)
- "low" (R=10)
- "skyship" (for Grails, open ntire map)

-"library"
-"fountain_of_fortune" (+2 luck)
-"mystic_pond"
-"mana_vortex"
-"portal_of_summoning"
-"ballista_yard"
-"freelancers_guild"
-"escape_tunnel"
-"artifact_merchant"
-"magic_university"

-"castle_gate"
Catle Gate is universal faction gate now.
It binds all players's towns which belong to one faction

-"creature_transformer" (only for vanila skeletons yet)
-"spellpower_garrison_bonus" (+2 sp)
-"attack_garrison_bonus" (+2 attack
-"defense_garrison_bonus" (+2 defence)

2020-09-30 20:40 UTC, alexvins requested changes

2020-09-30 20:40 UTC, alexvins commented on lib/CTownHandler.h
> +		h & height;
Missing backward compatibility handling.

2020-09-30 20:40 UTC, alexvins commented on lib/mapObjects/CGTownInstance.h
> +	CGTownBuilding() : town(nullptr) {};
IDs should also be initialized

2020-09-30 20:40 UTC, alexvins commented on lib/mapObjects/CGTownInstance.h
> +		h & bID;
Missing backward compatibility handling.

2020-09-30 20:40 UTC, alexvins commented on lib/CTownHandler.cpp
> +	for(const auto & kvp : map)
You should use `map::find()` here. Also there is an almost identical function `parseByMap` in JsonNode.cpp

2020-09-30 20:40 UTC, alexvins commented on lib/CTownHandler.cpp
> +		{ "mystic_pond", BuildingSubID::MYSTIC_POND },
Please use lowerCamelCase for JSON keys.

2020-10-02 07:35 UTC, alexvins requested changes

2020-10-02 07:35 UTC, alexvins commented on lib/mapObjects/CGTownInstance.cpp
> +		if (prop)
`prop` is not set anywhere,

2020-10-02 21:37 UTC, ShubusCorporation reviewed
@alexvins ,  builds are ok 
https://travis-ci.org/github/vcmi/vcmi/builds/732379045

2020-10-02 23:51 UTC, alexvins requested changes

2020-10-02 23:51 UTC, alexvins commented on lib/CTownHandler.h
> +			height = CBuilding::HEIGHT_NO_TOWER;
We should set orrect `height` and `subId` for old saves.

2020-10-02 23:51 UTC, alexvins commented on lib/mapObjects/CGTownInstance.h
> +			bType = BuildingSubID::NONE;
We should set correct `bType` for old saves.

2020-10-03 21:02 UTC, ShubusCorporation commented
It seems, at the moment of loading game from the old save, this information is already nowhere to take:

![load_old_save](https://user-images.githubusercontent.com/58867270/95001680-dafab080-05d4-11eb-951e-4665f6a7b85b.png)

2020-10-03 21:25 UTC, ShubusCorporation commented
Furthermore, in CTown the same approach is used and it does't carry about actual moat hexes:

`	template <typename Handler> void serialize(Handler &h, const int version)
	{
		h & names;
		h & faction;
		h & creatures;
		h & dwellings;
		h & dwellingNames;
		h & buildings;
		h & hordeLvl;
		h & mageLevel;
		h & primaryRes;
		h & warMachine;
		h & clientInfo;
		h & moatDamage;
		if(version >= 758)
		{
			h & moatHexes;
		}
		else if(!h.saving)
		{
			moatHexes = defaultMoatHexes();
		}
		h & defaultTavernChance;
	}`

2020-10-04 04:34 UTC, alexvins commented
> It seems, at the moment of loading from the old save, this information is already nowhere to take:
> 
An example of how to solve this is `CSpellHandler::update780`

2020-10-06 14:55 UTC, alexvins approved these changes

2020-10-10 22:44 UTC, ShubusCorporation commented
Any objections on merging this?

2020-10-11 21:19 UTC, merged