Launcher fixes2
vcmi/vcmi pull request #822
Opened 2022-09-05 07:01 UTC by DjWarmonger

- Fixed resizing of toolbar: https://bugs.vcmi.eu/view.php?id=2728
- Fixed icon update when a sub-mod is enabled or disabled: https://bugs.vcmi.eu/view.php?id=3217

2022-09-05 07:41 UTC, Nordsoft91 commented on launcher/modManager/cmodlistview_moc.cpp
> +	//Suprisingly model is not automagically connected to filter model
automagically - typo?

2022-09-05 07:44 UTC, Nordsoft91 commented on launcher/modManager/cmodlistview_moc.cpp
> +	connect(modModel, &CModListModel::dataChanged, filterModel, &QAbstractItemModel::dataChanged);
does it fix https://github.com/vcmi/vcmi/issues/812?

2022-09-05 07:58 UTC, kambala-decapitator approved these changes
looks good to me

2022-09-05 12:47 UTC, Nordsoft91 requested changes
Bug discovered

2022-09-05 16:12 UTC, Nordsoft91 commented on launcher/modManager/cmodmanager.cpp
> +	modList->modChanged(mod);
If you asking about bug https://github.com/vcmi/vcmi/pull/822#issuecomment-1236968223, it's a regression (new bug)

2022-09-05 17:27 UTC, nullkiller commented on launcher/modManager/cmodmanager.cpp
> +	modList->modChanged(mod);
Yes I meant it.

2022-09-08 05:57 UTC, nullkiller commented
> Tested the build. It has major issue (regression):
> 
> 1. Press "download and refresh repositories"
> 2. Remove mod available on the server (VCMI extras for instance)
> 3. Observe problem
> 
> Expected result: enable button is not available, red circle button should not be visible Actual result: removed mod is possible to be enabled, pressing enable you will observe error

@DjWarmonger do you plan to fix this?

2022-09-11 15:00 UTC, nullkiller commented
Please rebase on top of develop.

2022-10-01 07:32 UTC, closed without merging